// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJS2LKmk_8Cr75KsZTfVj4NT6xU7obS54',
    appId: '1:202748519700:web:6f08ec66dcc27a971b8e01',
    messagingSenderId: '202748519700',
    projectId: 'uomperapp',
    authDomain: 'uomperapp.firebaseapp.com',
    storageBucket: 'uomperapp.firebasestorage.app',
    measurementId: 'G-TN08W1RS80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnfAWNgnkQh_9iJsMk3mOVfPL3VjwQLA',
    appId: '1:202748519700:android:4a8f050e437f55721b8e01',
    messagingSenderId: '202748519700',
    projectId: 'uomperapp',
    storageBucket: 'uomperapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Th8X6ZMZFgJyOT7WlvIrgAZYTvphTCY',
    appId: '1:202748519700:ios:bada3ee26070b2471b8e01',
    messagingSenderId: '202748519700',
    projectId: 'uomperapp',
    storageBucket: 'uomperapp.firebasestorage.app',
    iosBundleId: 'com.example.uomPerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Th8X6ZMZFgJyOT7WlvIrgAZYTvphTCY',
    appId: '1:202748519700:ios:bada3ee26070b2471b8e01',
    messagingSenderId: '202748519700',
    projectId: 'uomperapp',
    storageBucket: 'uomperapp.firebasestorage.app',
    iosBundleId: 'com.example.uomPerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJS2LKmk_8Cr75KsZTfVj4NT6xU7obS54',
    appId: '1:202748519700:web:bc56831f4d6dfd9b1b8e01',
    messagingSenderId: '202748519700',
    projectId: 'uomperapp',
    authDomain: 'uomperapp.firebaseapp.com',
    storageBucket: 'uomperapp.firebasestorage.app',
    measurementId: 'G-TKHNF0H9NW',
  );
}
